### ISSUE TITLE
Bug Report for Translated strings!

### ISSUE THREAD

**Issue by vim-x** [Andrex2287/MIUI-13-UKRAINIAN#1]
Недо переклади прикріпляти тут!

**Comment by BusnjukAn** [comment]
PersonalAssistant
abc_menu_Видалити_shortcut_label (invalid name)
abc_menu_Пробіл_shortcut_label (invalid name)

**Comment by vim-x** [comment]
> PersonalAssistant abc_menu_Видалити_shortcut_label (invalid name) abc_menu_Пробіл_shortcut_label (invalid name)

**Comment by BusnjukAn** [comment]
Перевірте переклад з логу помилок - дуже багато подвійних рядків, не закритий апостраф і т.i.
https://translators.xiaomi.eu/XML_MIUI12-Ukrainian-uk.html
