### ISSUE TITLE
xiaomi.eu

### ISSUE THREAD

**Issue by ingbrzy** [Andrex2287/MIUI-13-UKRAINIAN#2]
add me, MarkH-UK And IgorEisberg as collaborators. 

thanks

**Comment by vim-x** [comment]
Ok wait few minutes!

**Comment by vim-x** [comment]
Done!

**Comment by ingbrzy** [comment]
no its not.. I didn't receive any invitation..

**Comment by vim-x** [comment]
Sorry wait 1 minute!

**Comment by Andrex2287** [comment]
![Screenshot_2022-06-05-07-53-33-551_com android chrome](https://user-images.githubusercontent.com/104192394/172037388-767cc107-d0f3-4a2b-96da-5e526841ace0.jpg)
![Screenshot_2022-06-05-07-53-37-861_com android chrome](https://user-images.githubusercontent.com/104192394/172037396-7e40308b-19d5-487e-a0a1-518c5e57e042.jpg)

**Comment by vim-x** [comment]
Fixed!
