### ISSUE TITLE
My device

### ISSUE THREAD

**Issue by FoxVol** [Andrex2287/MIUI-13-UKRAINIAN#3]
Refine the translation:
Battery capacity — Ємність батареї
CPU — ЦП (which means: Центральний Процесор)
RAM — ОЗП (which means: Оперативний Запам'ятовуючий Пристрій)
Camera — swapped front and rear cameras on all devices.

**Comment by vim-x** [comment]
Прикрипіть будь ласка скріншот.

**Comment by FoxVol** [comment]
![Screenshot_2022-06-05-16-33-46-851_com android settings](https://user-images.githubusercontent.com/106919460/172056837-e994c0ea-f278-4856-a98b-a0db868c62de.jpg)

**Comment by FoxVol** [comment]
> Прикрипіть будь ласка скріншот.

Або Poco X3 NFC: 
![IMG_20220605_170002_838](https://user-images.githubusercontent.com/106919460/172056874-eb91fd0a-f96f-417c-8c80-9c4a3e729643.jpg)
Також переплутані показники основної та фронтальної камери

**Comment by vim-x** [comment]
У пошуку apk як виправимо зразу вам відповімо!

**Comment by vim-x** [comment]
Також хочу застережети що ще не переведо: Календар і Загрузки до завтра усе буде виправлено!

**Comment by vim-x** [comment]
У вас є Telegram?

**Comment by FoxVol** [comment]
Так є: @foxvol

**Comment by vim-x** [comment]
Це ви? 
![Screenshot_2022-06-05-18-38-07-880_org telegram messenger](https://user-images.githubusercontent.com/104192394/172060956-6a7acc6b-e4e2-46d9-aad1-2d7be6194348.jpg)

**Comment by vim-x** [comment]
Застарілий репозиторій української мови!
Old repository of Ukrainian Language!
