### ISSUE TITLE
Де проходить процес перекладу, на якому сервісі?

### ISSUE THREAD

**Issue by bigvovan** [Andrex2287/MIUI-13-UKRAINIAN#5]
1. Де проходить процес перекладу, на якому сервісі? 

2. При переході з прошивки глобал на xiaomi.eu помітив що шрифт відрізняється сильно, чому така відмінність?

**Comment by vim-x** [comment]
1. В додатку Notepad++ і ручками.
2. Це на кожній китайській прошивці такий шрифт.
