### ISSUE TITLE
Translation miui 14 in mi 11 ultra

### ISSUE THREAD

**Issue by IntensivePro** [Andrex2287/MIUI-13-UKRAINIAN#6]
1. Settings menu
   1.1. "Послуги та зворотний зв'язк" change to "Послуги та зворотній зв'язок"
   1.2. "Rear display" change to "Задній екран"

2. Settings-My divice
   2.1. Replace camera info. Should be :
Передня 20MP
Основна 50MP+48MP+48MP
   2.2. "Detailed info and specs" change to "Детальна інформація"

3. Settings-Wi-Fi
   3.1. "Network acceleration" change to "Прискорення мережі"

4. Settings-programs-permission
   4.1. "Background autostart" change to    "Автозапуск у фоновому режимі"

**Comment by vim-x** [comment]
Репозиторій уже не оновлюється. Якщо ви хочете щось оновити в репозиторії можете зв'язатися зі мною у Telegram.

**Comment by IntensivePro** [comment]
Як вас знайти в телеграмі?

**Comment by vim-x** [comment]
t.me/zeroxone_yt
